//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.WordGame.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateAGame {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateAGame() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.WordGame.Language.CreateAGame", typeof(CreateAGame).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game answer:.
        /// </summary>
        public static string Game_answer_ {
            get {
                return ResourceManager.GetString("Game answer:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game name:.
        /// </summary>
        public static string Game_name_ {
            get {
                return ResourceManager.GetString("Game name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making a new game.
        /// </summary>
        public static string Making_a_new_game {
            get {
                return ResourceManager.GetString("Making a new game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of questions allowed:.
        /// </summary>
        public static string Number_of_questions_allowed_ {
            get {
                return ResourceManager.GetString("Number of questions allowed:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register the game.
        /// </summary>
        public static string Register_the_game {
            get {
                return ResourceManager.GetString("Register the game", resourceCulture);
            }
        }
    }
}
